name: Lint

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: 3.12

      - name: Lint with ruff
        run: |
          python -m pip install ruff
          ruff check src/
          ruff format --check src/
