on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build_on_macos:
    name: Build macOS wheels
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: evora_wheel ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build

      - name: Build wheels
        run: |
          pyproject-build -w

      - name: Build source
        run: |
          pyproject-build -s

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          twine upload dist/*
